apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upload-api
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: upload-api

  namespaceSelector:
    matchNames:
      - video-platform

  endpoints:
    - port: http
      path: /metrics
      interval: 15s