apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: worker
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: worker

  namespaceSelector:
    matchNames:
      - video-platform

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      