apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-nginx
  namespace: video-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-nginx
  template:
    metadata:
      labels:
        app: streaming-nginx
    spec:
      containers:
        - name: streaming-nginx
          image: mokshaithandla/streaming-nginx:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: processed-video-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: processed-video-storage
          persistentVolumeClaim:
            claimName: processed-video-pvc