apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-api
  namespace: video-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-api
  template:
    metadata:
      labels:
        app: upload-api
    spec:
      containers:
        - name: upload-api
          image: upload-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: raw-video-storage
              mountPath: /videos/raw
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: raw-video-storage
          persistentVolumeClaim:
            claimName: raw-video-pvc