apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-video-pvc
  namespace: video-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi